blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    # path(route="/", view=include('allauth.urls')),
    path(route="blogs", view=views.blog, name="blogs"),
    path(route="blog/<int:blog_id>", view=views.blogDetail, name="blog_detail"),
]

deepconcmind/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', view=views.dashbord, name='dashbord'),
    path(route='users/', view=include('accounts.urls'), name='accounts'),
    path(route='accounts/', view=include('allauth.urls')),
    path('mind/', include('mind.urls')),
    path(route='blog/', view=include('blog.urls')),
    path(route='profile/', view=include('profiles.urls')),
    path(route='how-to', view=views.howToDashbord, name='how_to_dashbord'),
    path(route='how-to-mind-ai', view=views.howToMindAi, name='how_to_mind_ai'),
    ]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "profile"

urlpatterns = [
    # path(route="/", view=include('allauth.urls')),
    path(route="profiles", view=views.profiles, name="profiles"),
    path(route="profile/<int:profile_id>", view=views.profileDetail, name="profile_detail"),
]

profiles/models.py
from django.db import models

# Create your models here.
class Skill(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    
class Qualification(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Profile(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.IntegerField()
    gender = models.CharField(max_length=50)
    image = models.ImageField(upload_to='profiles/')
    bio = models.TextField()
    skills = models.ManyToManyField(to=Skill)
    qualifications = models.ManyToManyField(to=Qualification)

    def __str__(self):
        return self.name

profiles/views.py
from django.shortcuts import render
from .models import Profile

# Create your views here.
def profiles(request):
    profiles = Profile.objects.all()
    context = {'profiles': profiles}
    template_name = 'profiles/profiles.html'
    return render(request=request, 
                  template_name=template_name, 
                  context=context)

def profileDetail(request, profile_id):
    profile = Profile.objects.get(id=profile_id)
    context = {'profile': profile}
    template_name = 'profiles/profile.html'
    return render(request=request, 
                  template_name=template_name, 
                  context=context)

profiles/templates/profiles/profile.html
<!-- Signin Page -->
{% extends 'base.html' %}
<!-- Page Title -->
{% block title %}
<title>Profile {{profile.name}}</title>
{% endblock title%}
<style></style>
<!-- Page Content -->
{% block content %}
<main class="h-full pb-16 overflow-y-auto p-4">
  <!-- Remove everything INSIDE this div to a really blank page -->
  <div
    class="p-y-2 relative min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
  >
    <img
      class="object-cover w-full h-32 rounded"
      src="/media/{{profile.image}}"
      alt=""
      aria-hidden="true"
    />
    <h2 class="text-2xl font-semibold text-gray-700 dark:text-gray-200">
      {{profile.name}}
    </h2>
    <div class="flex">
      <a href="tel:{{profile.phone}}" class="pr-2">
        <button
          class="flex items-center justify-between px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
        >
          Free Inital Call
        </button>
      </a>
      <a href="mailto:{{profile.email}}">
        <button
          class="flex items-center justify-between px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
        >
          Send an Email
        </button>
      </a>
    </div>
    <div class="text-gray-600 p-2 dark:text-gray-400">
      <h2 class="text-2xl font-semibold text-gray-700 dark:text-gray-200">
        Skills
      </h2>
      {% for skill in profile.skills.all %}
      <ul>
        <li>&rarr; {{skill}}</li>
      </ul>
      {% endfor %}
    </div>
    <div class="text-gray-600 p-2 dark:text-gray-400">
      <h2 class="text-2xl font-semibold text-gray-700 dark:text-gray-200">
        Qualifications
      </h2>
      {% for qualification in profile.qualifications.all %}
      <ul>
        <li>&rarr; {{qualification}}</li>
      </ul>
      {% endfor %}
    </div>
  </div>
</main>
<script>
  const h2s = document.querySelectorAll("h2");
  h2s.forEach((element) => {
    element.classList.add(
      "my-6",
      "text-2xl",
      "font-semibold",
      "text-gray-700",
      "dark:text-gray-200"
    );
  });
</script>
{% endblock content %}

profiles/templates/profiles/profiles.html
<!-- Signin Page -->
{% extends 'base.html' %}
<!-- Page Title -->
{% block title %}
<title>Profile</title>
{% endblock title%}
<!-- Page Content -->
{% block content %}
<!-- Load Social Account -->
{% load socialaccount %}
<main class="h-full pb-16 overflow-y-auto">
  <div class="container px-6 mx-auto grid">
    <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
      Mental Therapists, Counsellors and more.
    </h2>
    <!-- CTA -->
    <a
      class="flex items-center justify-between p-4 mb-8 text-sm font-semibold text-purple-100 bg-purple-600 rounded-lg shadow-md focus:outline-none focus:shadow-outline-purple"
      href=""
    >
      <div class="flex items-center text-center">
        Frequently Asked Questions
      </div>
    </a>
  </div>
  <section class="profiles">
    <div class="grid gap-6 mb-8 md:grid-cols-2">
      {% if profiles %} {% for profile in profiles %}
      <a href="{% url 'profile:profile_detail' profile.id %}" class="p-4">
        <div
          class="p-y-2 relative min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
        >
          <img
            class="object-cover w-full h-64 rounded"
            src="/media/{{profile.image}}"
            alt=""
            aria-hidden="true"
          />
          <p class="text-gray-600 p-2 dark:text-gray-400">{{profile.bio}}</p>
          <a
            href="{% url 'profile:profile_detail' profile.id %}"
            class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200"
          >
            VIEW PROFILE
          </a>
        </div>
      </a>
      {% endfor %} {% else %}
      <div class="min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
        <p class="text-gray-600 dark:text-gray-400">No profile found!</p>
        <h4 class="font-bold text-gray-600 dark:text-gray-400">
          {{profile.category}}
        </h4>
      </div>
      {% endif %}
    </div>
  </section>
</main>
{% endblock content %}