accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    # path(route="/", view=include('allauth.urls')),
    path(route="signup", view=views.signup, name="signup"),
    path(route="signin", view=views.signin, name="signin"),
    path(route="signout", view=views.signout, name="signout"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    # path(route="/", view=include('allauth.urls')),
    path(route="blogs", view=views.blog, name="blogs"),
    path(route="blog/<int:blog_id>", view=views.blogDetail, name="blog_detail"),
]

deepconcmind/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', view=views.dashbord, name='dashbord'),
    path(route='users/', view=include('accounts.urls'), name='accounts'),
    path(route='accounts/', view=include('allauth.urls')),
    path('mind/', include('mind.urls')),
    path(route='blog/', view=include('blog.urls')),
    path(route='profile/', view=include('profiles.urls')),
    path(route='how-to', view=views.howToDashbord, name='how_to_dashbord'),
    path(route='how-to-mind-ai', view=views.howToMindAi, name='how_to_mind_ai'),
    ]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# customize user model

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label='',
        required=True,
        widget=forms.TextInput(
            attrs={'placeholder': 'username', 
                   'class': 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input'}), 
        )
    email = forms.CharField(
        label='',
        required=True,
        widget=forms.EmailInput(
            attrs={'placeholder': 'email', 
                   'class': 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input'}), 
        )
    
    password1 = forms.CharField(
        required=True,
        label='',
        widget=forms.PasswordInput(
            attrs={'placeholder': 'password', 
                   'class': 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input'}), 
        )
    
    password2 = forms.CharField(
        required=True,
        label='',
        widget=forms.PasswordInput(
            attrs={'placeholder': 'confirm password', 
                   'class': 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input'}), 
        )

    class Meta:
        model = User  # Replace 'User' with your custom User model if you have one
        fields = ('username', 'email', 'password1', 'password2')


class CustomUserAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        required=True,
        label='',
        widget=forms.TextInput(
            attrs={'placeholder': 'username', 
                   'class': 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input'}), 
        )
    password = forms.CharField(
        required=True,
        label='',
        widget=forms.PasswordInput(
            attrs={'placeholder': 'password', 
                   'class': 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input'}), 
        )
    

    class Meta:
        model = User  # Replace 'User' with your custom User model if you have one
        fields = ('username', 'email', 'password1',)

accounts/views.py
from django.db.models import Q
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import login
from django.contrib.auth import logout
# from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm, CustomUserAuthenticationForm

from django.contrib.auth.forms import AuthenticationForm

# Create your views here.


def signin(request):
    if request.method == "POST":
        form = CustomUserAuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request=request, user=user)
            if 'next' in request.POST:
                return redirect(to=request.POST.get('next'))
            else:
                return redirect(to='/')
        else:
            error = 'Please enter correct username and password. Click "Create account" if you dont have an account.'
            template_name = 'accounts/signin.html'
            context = {'form': CustomUserAuthenticationForm(), 'error': error}
            return render(request, template_name=template_name, context=context)
    else:
        template_name = 'accounts/signin.html'
        context = {'form': CustomUserAuthenticationForm()}
    return render(request, template_name=template_name, context=context)



def signout(request):
    logout(request=request)
    return redirect(to='/')


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            # login user
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('/')
        else:
            # Customize error messages
            error = form.errors
            template_name = 'accounts/signup.html'
            context = {'form': CustomUserCreationForm(), 'error': error}
            return render(request, template_name=template_name, context=context)
    else:
        template_name = 'accounts/signup.html'
        context = {'form': CustomUserCreationForm()}
    return render(request=request, template_name=template_name, context=context)

accounts/templates/accounts/signin.html
<!-- Signin Page -->
{% extends 'base.html' %}
<!-- Page Title -->
{% block title %}
<title>SignIn</title>
{% endblock title%}
<!-- Page Content -->
{% block content %}
<!-- Load Social Account -->
{% load socialaccount %}
<main class="h-full pb-16 overflow-y-auto">
  <div class="container px-6 mx-auto grid">
    <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
      Welcome back, login
    </h2>
    <!-- CTA -->
    <a
      class="flex items-center justify-between p-4 mb-8 text-sm font-semibold text-purple-100 bg-purple-600 rounded-lg shadow-md focus:outline-none focus:shadow-outline-purple"
      href="{% provider_login_url 'google' %}?next=/"
    >
      <div class="flex items-center text-center">Login with Google</div>
    </a>
    <!-- General elements -->
    <h4
      class="text-center mb-4 text-lg font-semibold text-gray-600 dark:text-gray-300"
    >
      Or
    </h4>
    <div
      class="px-4 pt-3 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800"
    >
      <form action="{% url 'accounts:signin' %}" method="post">
        {% csrf_token %}
        <!-- Show Errors -->
        {% if error %}
        <div
          class="error min-w-0 p-4 text-white bg-purple-600 rounded-lg shadow-xs"
        >
          <h4 class="mb-4 font-semibold">Error</h4>
          <p>{{error}}</p>
        </div>
        {% endif %}
        <div class="mt-3">{{form}}</div>
        <div class="flex mt-1 justify-center">
          <button
            type="submit"
            class="w-full px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-md active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
          >
            Login
          </button>
        </div>
        <div>
          <p class="mt-3">
            <a
              class="text-sm font-medium text-purple-600 dark:text-purple-400 hover:underline"
              href="{% url 'accounts:signup' %}"
            >
              Create account
            </a>
          </p>
        </div>
      </form>
    </div>
  </div>
</main>

{% endblock content %}

accounts/templates/accounts/signup.html
<!-- Signin Page -->
{% extends 'base.html' %}
<!-- Page Title -->
{% block title %}
<title>SignUp</title>
{% endblock title%}
<!-- Page Content -->
{% block content %}
<!-- Load Social Account -->
{% load socialaccount %}
<main class="h-full pb-16 overflow-y-auto">
  <div class="container px-6 mx-auto grid">
    <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
      Welcome back, SignUp
    </h2>
    <!-- CTA -->
    <a
      class="flex items-center justify-between p-4 mb-8 text-sm font-semibold text-purple-100 bg-purple-600 rounded-lg shadow-md focus:outline-none focus:shadow-outline-purple"
      href="{% provider_login_url 'google' %}?next=/"
    >
      <div class="flex items-center text-center">SignUp with Google</div>
    </a>
    <!-- General elements -->
    <h4
      class="text-center mb-4 text-lg font-semibold text-gray-600 dark:text-gray-300"
    >
      Or
    </h4>
    <div
      class="px-4 pt-3 py-3 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800"
    >
      <form action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        <!-- Show Errors -->
        {% if error %}
        <div
          class="error min-w-0 p-4 text-white bg-purple-600 rounded-lg shadow-xs"
        >
          <h4 class="mb-4 font-semibold">Error</h4>
          <p>{{error}}</p>
        </div>
        {% endif %}
        <div class="mt-3">{{form}}</div>
        <div class="flex mt-1 justify-center">
          <button
            type="submit"
            class="w-full px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-md active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
          >
            Signup
          </button>
        </div>
        <div>
          <p class="mt-3">
            <a
              class="text-sm text-center font-medium text-purple-600 dark:text-purple-400 hover:underline"
              href="{% url 'accounts:signin' %}"
            >
              Login
            </a>
          </p>
        </div>
      </form>
    </div>
  </div>
</main>

{% endblock content %}