blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    # path(route="/", view=include('allauth.urls')),
    path(route="blogs", view=views.blog, name="blogs"),
    path(route="blog/<int:blog_id>", view=views.blogDetail, name="blog_detail"),
]

deepconcmind/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', view=views.dashbord, name='dashbord'),
    path(route='users/', view=include('accounts.urls'), name='accounts'),
    path(route='accounts/', view=include('allauth.urls')),
    path('mind/', include('mind.urls')),
    path(route='blog/', view=include('blog.urls')),
    path(route='profile/', view=include('profiles.urls')),
    path(route='how-to', view=views.howToDashbord, name='how_to_dashbord'),
    path(route='how-to-mind-ai', view=views.howToMindAi, name='how_to_mind_ai'),
    ]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=200)
    bio = models.TextField()

    def __str__(self):
        return self.name
    
class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')
    pub_date = models.DateTimeField('date published')
    body = models.TextField()

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:200]

blog/views.py
from django.shortcuts import render
from .models import Blog
import markdown

# Create your views here.
def blog(request):
    blogs = Blog.objects.all()
    context = {'blogs' : blogs}
    template_name = 'blog/blogs.html'
    return render(request=request,
                  template_name=template_name,
                  context= context)

def blogDetail(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    related_blogs = Blog.objects.filter(category=blog.category).order_by('-id')[:3]
    context = {
        'blog' : blog,
        'details': markdown.markdown(blog.body),
        'related_blogs' : related_blogs
        }
    template_name = 'blog/blog_detail.html'
    return render(request=request,
                  template_name=template_name,
                  context= context)

blog/templates/blog/blog_detail.html
<!-- Signin Page -->
{% extends 'base.html' %}
<!-- Page Title -->
{% block title %}
<title>{{blog.title}}</title>
{% endblock title%}
<style></style>
<!-- Page Content -->
{% block content %}
<main class="h-full pb-16 overflow-y-auto">
  <!-- Remove everything INSIDE this div to a really blank page -->
  <div
    class="p-y-2 relative min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
  >
    <img
      class="object-cover w-full h-32 rounded"
      src="/media/{{blog.image}}"
      alt=""
      aria-hidden="true"
    />
    <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
      {{blog.title}}
    </h2>
    <div class="text-gray-600 p-2 dark:text-gray-400">{{details|safe}}</div>
  </div>
</main>
<script>
  const h2s = document.querySelectorAll("h2");
  h2s.forEach((element) => {
    element.classList.add(
      "my-6",
      "text-2xl",
      "font-semibold",
      "text-gray-700",
      "dark:text-gray-200"
    );
  });
</script>
{% endblock content %}

blog/templates/blog/blogs.html
<!-- Signin Page -->
{% extends 'base.html' %}
<!-- Page Title -->
{% block title %}
<title>Blog</title>
{% endblock title%}
<!-- Page Content -->
{% block content %}
<!-- Load Social Account -->
{% load socialaccount %}
<main class="h-full pb-16 overflow-y-auto">
  <div class="container px-6 mx-auto grid">
    <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
      Mental health articles, blogs and stories
    </h2>
    <!-- CTA -->
    <a
      class="flex items-center justify-between p-4 mb-8 text-sm font-semibold text-purple-100 bg-purple-600 rounded-lg shadow-md focus:outline-none focus:shadow-outline-purple"
      href=""
    >
      <div class="flex items-center text-center">
        Frequently Asked Questions
      </div>
    </a>
  </div>
  <section class="blogs">
    <div class="grid gap-6 mb-8 md:grid-cols-2">
      {% if blogs %} {% for blog in blogs %}
      <a href="{% url 'blog:blog_detail' blog.id %}" class="p-4">
        <div
          class="p-y-2 relative min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
        >
          <img
            class="object-cover w-full h-64 rounded"
            src="/media/{{blog.image}}"
            alt=""
            aria-hidden="true"
          />
          <p class="text-gray-600 p-2 dark:text-gray-400">{{blog.summary}}</p>
          <h2
            class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200"
          >
            {{blog.category}}
          </h2>
        </div>
      </a>
      {% endfor %} {% else %}
      <div class="min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
        <p class="text-gray-600 dark:text-gray-400">No blog found!</p>
        <h4 class="font-bold text-gray-600 dark:text-gray-400">
          {{blog.category}}
        </h4>
      </div>
      {% endif %}
    </div>
  </section>
</main>
{% endblock content %}