blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    # path(route="/", view=include('allauth.urls')),
    path(route="blogs", view=views.blog, name="blogs"),
    path(route="blog/<int:blog_id>", view=views.blogDetail, name="blog_detail"),
]

deepconcmind/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', view=views.dashbord, name='dashbord'),
    path(route='users/', view=include('accounts.urls'), name='accounts'),
    path(route='accounts/', view=include('allauth.urls')),
    path('mind/', include('mind.urls')),
    path(route='blog/', view=include('blog.urls')),
    path(route='profile/', view=include('profiles.urls')),
    path(route='how-to', view=views.howToDashbord, name='how_to_dashbord'),
    path(route='how-to-mind-ai', view=views.howToMindAi, name='how_to_mind_ai'),
    ]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mind/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include

app_name = 'mind'

urlpatterns = [
    path('chat/', view=views.mind, name='chat'),
    path(route='delete', view=views.deleteChat, name='delete'),
]

profiles/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "profile"

urlpatterns = [
    # path(route="/", view=include('allauth.urls')),
    path(route="profiles", view=views.profiles, name="profiles"),
    path(route="profile/<int:profile_id>", view=views.profileDetail, name="profile_detail"),
]

mind/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
User = get_user_model()

class Chat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    human = models.TextField()
    mind_bot = models.TextField()
    def __str__(self):
        return self.user.username
    

class Secret(models.Model):
    name = models.CharField(max_length=100)
    secret = models.TextField()
    def __str__(self):
        return self.name

mind/views.py
import os
import json
# import django tools
from django.shortcuts import render, redirect
from django.http import JsonResponse
# # import langchain tools
from langchain.llms import OpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import ConversationChain
from langchain.memory import ConversationBufferWindowMemory
from django.contrib.auth.decorators import login_required
from .models import Chat
from .models import Secret

# Memory Dictionary
memory_dict = {}
def askOpenAI(message:str, memory):
    os.environ['OPENAI_API_KEY'] = Secret.objects.get(name='openai_key').secret
    llm = OpenAI(temperature=0)

    prompt = PromptTemplate(
    input_variables=['history', 'input'],
    template="""
    A conversation between a human and a Deep Conclusions Mind bot specialized in mental health counseling:

    EXAMPLES:

    Human: I'm swamped with work and life, and feeling pretty down. Any advice?
    Bot: What aspects of your life are causing the most stress? Knowing specifics can help me offer useful strategies.

    Human: Work is eating up all my time. I'm missing out on family moments.
    Bot: Can you break down your daily tasks for me? This can help us find gaps where you can spend time with family.

    Human: Could planning help me get more time back?
    Bot: Absolutely. Creating a structured plan and possibly delegating tasks can be effective.

    Human: Do you think this will really make a difference?
    Bot: Every journey starts with a first step. Try it out and tweak as needed. Feel free to reach out for adjustments.

    Current conversation:
    {history}
    Human: {input}
    Mind Bot:
    """,
    # System-specific guidelines
    rules={
        'system_query': 'I am a specialized mental health counsellor bot created by Deep Conclusions.',
        'off_topic': 'My expertise is solely in the area of mental health.'
    }
    )



    chain = ConversationChain(llm=llm,prompt=prompt, memory=memory)

    response = chain({"input": message})

    return response['response']

@login_required(login_url='accounts:signin')
def mind(request):
    user_id = str(request.user.id)
    if user_id not in memory_dict:
        memory_dict[user_id] = ConversationBufferWindowMemory()

    if request.method == 'POST':
        data = json.loads(request.body)
        clean_message = str(data['message'])
        response = askOpenAI(clean_message, memory_dict[user_id])
        print(response)
        chat = Chat(user=request.user, human=clean_message, mind_bot=response)
        chat.save()
        return JsonResponse({"message": clean_message, "response": response})
    else:
        chats = Chat.objects.filter(user=request.user)
        context = {'history': chats}
        template_name = 'mind/mind.html'
        return render(request=request, template_name=template_name, context=context)


def deleteChat(request):
    Chat.objects.filter(user=request.user).delete()
    return redirect(request.META['HTTP_REFERER'])

templates/dashbord.html
{% extends 'base.html' %}
<!-- Page Title -->
{% block title %}
<title>Dashbord</title>
{% endblock title%}
<!-- Page Content -->
{% block content %}
<main class="h-full overflow-y-auto">
  <div class="container px-6 mx-auto grid">
    <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
      Dashboard
    </h2>
    <!-- CTA -->
    <a
      class="flex items-center justify-between p-4 mb-8 text-sm font-semibold text-purple-100 bg-purple-600 rounded-lg shadow-md focus:outline-none focus:shadow-outline-purple"
      href=""
    >
      <div class="flex items-center">
        <svg class="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
          <path
            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
          ></path>
        </svg>
        <span>Frequently Asked Questions</span>
      </div>
      <span>View more &RightArrow;</span>
    </a>
    <!-- Cards -->
    <div class="grid gap-6 mb-8 md:grid-cols-2 xl:grid-cols-4">
      <!-- Card -->
      <div
        class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
      >
        <div
          class="p-3 mr-4 text-teal-500 bg-teal-100 rounded-full dark:text-teal-100 dark:bg-teal-500"
        >
          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
            <path
              fill-rule="evenodd"
              d="M18 5v8a2 2 0 01-2 2h-5l-5 4v-4H4a2 2 0 01-2-2V5a2 2 0 012-2h12a2 2 0 012 2zM7 8H5v2h2V8zm2 0h2v2H9V8zm6 0h-2v2h2V8z"
              clip-rule="evenodd"
            ></path>
          </svg>
        </div>
        <a href="{% url 'mind:chat'%}">
          <p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">
            Our ai
          </p>
          <p class="text-lg font-semibold text-gray-700 dark:text-gray-200">
            Ask Mind
          </p>
        </a>
      </div>
      <!-- Card -->
      <div
        class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
      >
        <div
          class="p-3 mr-4 text-blue-500 bg-blue-100 rounded-full dark:text-blue-100 dark:bg-blue-500"
        >
          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
            <path
              fill-rule="evenodd"
              d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z"
              clip-rule="evenodd"
            ></path>
          </svg>
        </div>
        <a href="{% url 'blog:blogs' %}">
          <p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">
            Helpful Articles
          </p>
          <p class="text-lg font-semibold text-gray-700 dark:text-gray-200">
            Resources
          </p>
        </a>
      </div>
      <!-- Card -->
      <div
        class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
      >
        <div
          class="p-3 mr-4 text-orange-500 bg-orange-100 rounded-full dark:text-orange-100 dark:bg-orange-500"
        >
          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
            <path
              d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z"
            ></path>
          </svg>
        </div>
        <a href="{% url 'profile:profiles' %}">
          <p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">
            Meet someone
          </p>
          <p class="text-lg font-semibold text-gray-700 dark:text-gray-200">
            Medical Personnel
          </p>
        </a>
      </div>
    </div>

    <!-- Charts -->
    <h2
      class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200"
      id="charts"
    >
      Charts
    </h2>
    <div class="grid gap-6 mb-8 md:grid-cols-2">
      <div class="min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
        <h4 class="mb-4 font-semibold text-gray-800 dark:text-gray-300">
          States Doughnut
        </h4>
        <canvas id="pie"></canvas>
        <div
          class="flex justify-center mt-4 space-x-3 text-sm text-gray-600 dark:text-gray-400"
        >
          <!-- Chart legend -->
          <div class="flex items-center">
            <span
              class="inline-block w-3 h-3 mr-1 bg-blue-500 rounded-full"
            ></span>
            <span>Pass</span>
          </div>
          <div class="flex items-center">
            <span
              class="inline-block w-3 h-3 mr-1 bg-teal-600 rounded-full"
            ></span>
            <span>Depression</span>
          </div>
          <div class="flex items-center">
            <span
              class="inline-block w-3 h-3 mr-1 bg-purple-600 rounded-full"
            ></span>
            <span>Stress</span>
          </div>
        </div>
      </div>
      <div class="min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
        <h4 class="mb-4 font-semibold text-gray-800 dark:text-gray-300">
          Trends
        </h4>
        <canvas id="line"></canvas>
        <div
          class="flex justify-center mt-4 space-x-3 text-sm text-gray-600 dark:text-gray-400"
        >
          <!-- Chart legend -->
          <div class="flex items-center">
            <span
              class="inline-block w-3 h-3 mr-1 bg-teal-600 rounded-full"
            ></span>
            <span>Stress</span>
          </div>
          <div class="flex items-center">
            <span
              class="inline-block w-3 h-3 mr-1 bg-purple-600 rounded-full"
            ></span>
            <span>Depression</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

templates/how_to_dashbord.html
{% extends 'base.html' %}
<!-- Page title -->
{% block title %}
<title>How To Dashbord</title>
{% endblock title %}
<!-- Page Content -->
{% block content %}
<main class="h-full overflow-y-auto text-gray-700 dark:text-gray-200">
  <iframe
    src="https://app.tango.us/app/embed/2562cb25-fd9e-4452-9e2d-37803523e3e1"
    sandbox="allow-scripts allow-top-navigation-by-user-activation allow-popups allow-same-origin"
    security="restricted"
    title="Navigating the Dashboard: How to Access Account Features, Login, Articles, Charts, and More"
    width="100%"
    height="100%"
    referrerpolicy="strict-origin-when-cross-origin"
    frameborder="0"
    webkitallowfullscreen="webkitallowfullscreen"
    mozallowfullscreen="mozallowfullscreen"
    allowfullscreen="allowfullscreen"
  ></iframe>
</main>
{% endblock content%}

templates/how_to_mind_ai.html
{% extends 'base.html' %}
<!-- Page title -->
{% block title %}
<title>How To MindAi</title>
{% endblock title %}
<!-- Page Content -->
{% block content %}
<iframe
  src="https://app.tango.us/app/embed/776248f7-c6f7-4d90-b192-269a6cae0858"
  sandbox="allow-scripts allow-top-navigation-by-user-activation allow-popups allow-same-origin"
  security="restricted"
  title="Chatting with Our MindAi"
  width="100%"
  height="100%"
  referrerpolicy="strict-origin-when-cross-origin"
  frameborder="0"
  webkitallowfullscreen="webkitallowfullscreen"
  mozallowfullscreen="mozallowfullscreen"
  allowfullscreen="allowfullscreen"
></iframe>
{% endblock content %}

templates/mind.html
{% extends 'base.html' %} {% block content %}
<main class="h-full pb-16 overflow-y-auto">
  <div class="container px-6 mx-auto grid">
    <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200">
      MindAI
    </h2>
    <!-- CTA -->
    <a
      class="flex items-center justify-between p-4 mb-8 text-sm font-semibold text-purple-100 bg-purple-600 rounded-lg shadow-md focus:outline-none focus:shadow-outline-purple"
      href="https://github.com/estevanmaito/windmill-dashboard"
    >
      <div class="flex items-center">
        <svg class="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
          <path
            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
          ></path>
        </svg>
        <span>Star this project on GitHub</span>
      </div>
      <span>View more &RightArrow;</span>
    </a>

    {% if history %}
    <div class="flex flex-col history">
      {% for story in history %}
      <div
        class="mb-4 min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800"
      >
        <h4 class="mb-4 font-semibold text-gray-600 dark:text-gray-300">
          {{story.user.username}}
        </h4>
        <p class="text-gray-600 dark:text-gray-400">{{story.message}}</p>
      </div>
      <!-- Response -->
      <div
        class="mb-4 min-w-0 p-4 text-white bg-purple-600 rounded-lg shadow-xs"
      >
        <h4 class="mb-4 font-semibold">Mind</h4>
        <p>{{story.response}}</p>
      </div>
      {% endfor%}
    </div>
    {% else %}
    <div class="min-w-0 p-4 text-white bg-purple-600 rounded-lg shadow-xs">
      <h4 class="mb-4 font-semibold">Mind</h4>
      <p>Hi {{request.user.username}} 👋, Let's Talk</p>
    </div>
    {% endif %}

    <!-- General elements -->
    <form
      action="{% url 'mind:chat' %}"
      method="post"
      class="px-4 py-3 mt-6 mb-8 bg-white rounded-lg shadow-md dark:bg-gray-800"
    >
      {% csrf_token %}
      <label class="block mt-4 text-sm">
        <div class="relative text-gray-500 focus-within:text-purple-600">
          <input
            class="block w-full pr-20 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input"
            placeholder="Say something "
            name="message"
          />
          <button
            class="absolute inset-y-0 right-0 px-4 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-r-md active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple"
          >
            Send
          </button>
        </div>
      </label>
      <a href="{% url 'mind:delete' %}" class="flex mt-1 justify-center">
        <button
          type="button"
          class="w-full px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-red-600 border border-transparent rounded-md active:bg-red-600 hover:bg-red-700 focus:outline-none focus:shadow-outline-red"
        >
          Clear Chat
        </button>
      </a>
    </form>
  </div>
</main>
{% endblock content %}